### ISSUE TITLE
File missing of ubuntu64-1.img

### ISSUE THREAD

**Issue by xwuxjim333** [14gr1010/software#1]
Hello, I really want to run this project on my computer and try SDN with KODO library.
But your link : https://dl.dropboxusercontent.com/u/2347095/virtuals.tar.bz2 is not available now.
Can you please recover this?
I've read a paper "Network Coded Software Defined Networking: Enabling 5G Transmission and Storage Networks" , that tells me about this project you made.
Now I want to build this but failed.
Or there is some replacement of the image file?
Please recover the file or tell me how to replace this if there is another way.
Thank you very much !!!

**Comment by aloooha** [comment]
In folder "virtual_setup", you could find how to download the img( link: http://kom.aau.dk/group/13gr810/virtuals.tar.bz2).

**Comment by hrjonashansen** [comment]
An alternative download mirror: https://www.dropbox.com/s/qucjmillkuo1t25/virtuals.tar.bz2?dl=0
Has been added.
